"""User-deletion

Revision ID: 03964e673317
Revises: 6c7a76da000e
Create Date: 2024-09-17 11:19:21.153510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03964e673317'
down_revision = '6c7a76da000e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.drop_constraint('flocks_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_constraint('health_records_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_constraint('production_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('production_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inventory_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('health_records_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('flocks_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
