"""Add arrival date for flock2

Revision ID: 34f83d5d8e05
Revises: 9957c5c98ccd
Create Date: 2024-09-14 17:23:11.034846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34f83d5d8e05'
down_revision = '9957c5c98ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('arrival_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
