"""Remove flock and production relationship

Revision ID: 7108dcb75ec0
Revises: b2911315a84e
Create Date: 2024-09-11 11:38:32.820179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7108dcb75ec0'
down_revision = 'b2911315a84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_eggs_collected', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_production_flock_id')
        batch_op.drop_constraint('production_flock_id_fkey', type_='foreignkey')
        batch_op.drop_column('flock_id')
        batch_op.drop_column('eggs_collected')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eggs_collected', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('flock_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('production_flock_id_fkey', 'flocks', ['flock_id'], ['id'])
        batch_op.create_index('ix_production_flock_id', ['flock_id'], unique=False)
        batch_op.drop_column('number_eggs_collected')

    # ### end Alembic commands ###
