"""Add age instead of age_week

Revision ID: 77dd7ac74d67
Revises: 7108dcb75ec0
Create Date: 2024-09-11 12:12:53.946795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dd7ac74d67'
down_revision = '7108dcb75ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.drop_column('age_weeks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_weeks', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
