"""Add username to user model

Revision ID: 83e5de9401ea
Revises: b71b0d3c3ae7
Create Date: 2024-09-07 20:13:27.518333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e5de9401ea'
down_revision = 'b71b0d3c3ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('WORKER', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('farms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_farms_owner_id'), ['owner_id'], unique=False)

    op.create_table('flocks',
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('age_weeks', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flocks_farm_id'), ['farm_id'], unique=False)

    op.create_table('health_records',
    sa.Column('health_status', sa.String(length=200), nullable=False),
    sa.Column('health_issue', sa.String(length=200), nullable=False),
    sa.Column('medication_given', sa.String(length=200), nullable=False),
    sa.Column('date_reported', sa.DateTime(), nullable=False),
    sa.Column('vaccinated', sa.Boolean(), nullable=True),
    sa.Column('vaccination_date', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_records_farm_id'), ['farm_id'], unique=False)

    op.create_table('inventory',
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'item_name', 'purchase_date', name='unique_inventory_entry')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_farm_id'), ['farm_id'], unique=False)

    op.create_table('production',
    sa.Column('eggs_collected', sa.Integer(), nullable=False),
    sa.Column('eggs_sold', sa.Integer(), nullable=True),
    sa.Column('date_collected', sa.DateTime(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_flock_id'), ['flock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_flock_id'))
        batch_op.drop_index(batch_op.f('ix_production_farm_id'))

    op.drop_table('production')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_farm_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_category'))

    op.drop_table('inventory')
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_records_farm_id'))

    op.drop_table('health_records')
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flocks_farm_id'))

    op.drop_table('flocks')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_owner_id'))
        batch_op.drop_index(batch_op.f('ix_farms_location'))

    op.drop_table('farms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
