"""Remove vaccination

Revision ID: 8b5769c03e80
Revises: f2f13871e02b
Create Date: 2024-09-11 19:32:34.116462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b5769c03e80'
down_revision = 'f2f13871e02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('vaccination_date')
        batch_op.drop_column('vaccinated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccinated', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vaccination_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
