"""Arrange health records to only capture sick birds

Revision ID: 94d79299d73a
Revises: 8b5769c03e80
Create Date: 2024-09-11 19:49:22.925011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d79299d73a'
down_revision = '8b5769c03e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('health_status')
        batch_op.drop_column('number_not_sick')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_not_sick', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('health_status', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
