"""Add arrival date for flock

Revision ID: 9957c5c98ccd
Revises: a352be7d4af4
Create Date: 2024-09-14 17:18:32.399956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9957c5c98ccd'
down_revision = 'a352be7d4af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.drop_column('arrival_date')

    # ### end Alembic commands ###
