"""Add number of chicken sick and not sick in health record

Revision ID: af3939d7adef
Revises: 77dd7ac74d67
Create Date: 2024-09-11 19:23:33.631545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3939d7adef'
down_revision = '77dd7ac74d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_sick', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number_not_sick', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('number_not_sick')
        batch_op.drop_column('number_sick')

    # ### end Alembic commands ###
