"""Add currency option

Revision ID: b2911315a84e
Revises: d35433ca167c
Create Date: 2024-09-11 09:16:57.952285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2911315a84e'
down_revision = 'd35433ca167c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.alter_column('vaccination_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.alter_column('vaccination_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
