"""User-deletion2

Revision ID: e1d48e18a9f0
Revises: 03964e673317
Create Date: 2024-09-17 12:22:20.081272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d48e18a9f0'
down_revision = '03964e673317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_username', sa.String(length=100), nullable=True))

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_username', sa.String(length=100), nullable=True))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_username', sa.String(length=100), nullable=True))

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_username', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_column('created_by_username')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('created_by_username')

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('created_by_username')

    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.drop_column('created_by_username')

    # ### end Alembic commands ###
