"""Update

Revision ID: e775a2ba173f
Revises: 06a5a1155e7d
Create Date: 2024-09-13 13:36:38.789405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e775a2ba173f'
down_revision = '06a5a1155e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
