"""Add symptom

Revision ID: f2f13871e02b
Revises: af3939d7adef
Create Date: 2024-09-11 19:26:22.034500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f13871e02b'
down_revision = 'af3939d7adef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptom', sa.String(length=200), nullable=False))
        batch_op.drop_column('health_issue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_issue', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('symptom')

    # ### end Alembic commands ###
